kind: pipeline
name: default

steps:
- name: tests_compilation
  image: rikorose/gcc-cmake
  commands:
  - mkdir extras/test/build
  - cd extras/test/build
  - cmake ..
  - make -j32

- name: tests
  image: rikorose/gcc-cmake
  commands:
  - cd extras/test/build
  - ./supladevicetests --gtest_repeat=50 --gtest_shuffle
  depends_on:
  - tests_compilation

- name: esp8266_rtos_compilation_check
  image: devel/esp8266_rtos_sdk
  pull: never
  commands:
  - pwd
  - echo $SUPLA_DEVICE_PATH
  - ls -al
  - export SUPLA_DEVICE_PATH=/drone/src
  - cd extras/examples/empty_esp8266_rtos_sdk_project/
  - rm -f build/supla-empty-esp8266-mk.bin
  - /bin/bash -c "source /supla/esp/ESP8266_RTOS_SDK/export.sh && make -j32"
  - /bin/bash -c "[ -f build/supla-empty-esp8266-mk.bin ] && true || false"

- name: rocket
  image: mike1pol/drone-rocket
  settings:
    url:
      from_secret: rocket_url
    user_id:
      from_secret: rocket_user_id
    token:
      from_secret: rocket_token
    channel: github
    avatar_url: "https://miro.medium.com/max/256/0*AqO_2lNemh_Fl9Gm.png"
  when:
    status: [success, failure]
    event:
      exclude:
        - pull_request
  depends_on: [tests, esp8266_rtos_compilation_check]

