kind: pipeline
name: default

steps:
- name: tests_compilation
  image: rikorose/gcc-cmake
  commands:
  - mkdir extras/test/build
  - cd extras/test/build
  - cmake ..
  - make -j32

- name: tests
  image: rikorose/gcc-cmake
  commands:
  - cd extras/test/build
  - ./supladevicetests --gtest_repeat=50 --gtest_shuffle
  depends_on:
  - tests_compilation

- name: esp8266_rtos_compilation_check
  image: devel/esp8266_rtos_sdk
  commands:
  - pwd
  - echo $SUPLA_DEVICE_PATH

- name: rocket
  image: mike1pol/drone-rocket
  settings:
    url:
      from_secret: rocket_url
    user_id:
      from_secret: rocket_user_id
    token:
      from_secret: rocket_token
    channel: github
    avatar_url: "https://miro.medium.com/max/256/0*AqO_2lNemh_Fl9Gm.png"
  when:
    status: [success, failure]
    event:
      exclude:
        - pull_request
  depends_on: [tests, esp8266_rtos_compilation_check]

